name: PHP Code Quality

on:
  pull_request:

jobs:
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-latest

    outputs:
      stepOutputs: ${{ steps.get-changed-files.outputs.files }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files
        id: get-changed-files
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.php$')"

  phpcs:
    name: PHPCS Check
    runs-on: ubuntu-latest

    needs: get-changed-files

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      # - name: Check PHPCS issues
      #   run: vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

      - name: Check PHPCS issues on modified lines
        run: |
          changed_files="${{ needs.get-changed-files.outputs.stepOutputs }}"
          if [ -n "$changed_files" ]; then
            git diff --unified=0 --no-prefix ${{ github.event.before }} ${{ github.sha }} -- $changed_files | tail -n +4 | grep -E '^[+-]' | grep '.php$' | sed -e 's/^[+-]//g' | xargs -r vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6-
          fi

  phpcbf:
    name: PHPCBF Fix
    runs-on: ubuntu-latest
    needs: phpcs
    if: ${{ needs.phpcs.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Fix PHPCBF issues
        run: vendor/bin/phpcbf --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

  pre-commit:
    name: Pre-commit hook
    runs-on: ubuntu-latest
    needs: phpcbf

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Check PHPCS issues on changed files
        run: |
          git diff --name-only HEAD^..HEAD | grep '.php$' | xargs -r vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6-
