name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHPCS
        # Get the changed files from the PR via Github CLI.
        # `grep` to only PHP files then remove deleted files via `find`.
        # Run `phpcs` on the remaining files and pass output to `cs2pr`.
        run: |
          echo "Files for this PR:"
          gh pr diff ${{ github.event.number }} --name-only | grep .php | xargs find 2> /dev/null | cat
          gh pr diff ${{ github.event.number }} --name-only | grep .php | xargs find 2> /dev/null | xargs phpcs -nq --report=checkstyle | cs2pr

  phpcbf:
    name: PHPCBF Fix
    runs-on: ubuntu-latest
    needs: phpcs
    if: ${{ needs.phpcs.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Fix PHPCBF issues
        run: vendor/bin/phpcbf --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

  pre-commit:
    name: Pre-commit hook
    runs-on: ubuntu-latest
    needs: phpcbf

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Check PHPCS issues on changed files
        run: |
          git diff --name-only HEAD^..HEAD | grep '.php$' | xargs -r vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6-
