name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs_check:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate diff
        run: |
          if [[ $(git rev-parse --abbrev-ref HEAD) == "main" || $(git rev-parse --abbrev-ref HEAD) == "master" ]]; then
            base_branch=$(git rev-parse HEAD)
          else
            base_branch=$(git merge-base HEAD main)
          fi
          git diff --name-only $base_branch HEAD > diff.txt
        shell: bash

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Composer install
        run: |
          composer install

      - name: Install Coverage
        run: composer require --dev exussum12/coverage-checker

      - name: Run PHPCS only on changed files
        run: |
          cat diff.txt | xargs phpcs --standard=PSR12 --report=json > phpcs.json || true
        shell: bash

      - name: Run diffFilter
        run: |
          ./vendor/bin/diffFilter --phpcs diff.txt phpcs.json 100
        shell: bash
