name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs_check:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Run PHPCBF
        run: vendor/bin/phpcbf --standard=PSR12 .

      - name: Commit changes (if any)
        run: |
          git diff --exit-code --quiet || git commit -am "Fix coding standards issues" && git push origin HEAD:$GITHUB_REF
        env:
          GITHUB_REF: ${{ github.head_ref }}
