name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs_check:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - uses: actions/checkout@v2
      - name: VIPCS check
        uses: 10up/wpcs-action@stable
        with:
          standard: "WordPress-VIP-Go"
          extra_args: "--report-json=./phpcs.json"
      - name: Update summary
        run: |
          npx --yes github:10up/phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
          cat phpcs.md >> $GITHUB_STEP_SUMMARY
        if: always()
