name: PHP Code Quality

on:
  pull_request:

jobs:
  get-default-branch:
    name: Get Default Branch
    runs-on: ubuntu-latest

    steps:
      - name: Get default branch name
        id: get_default_branch
        run: |
          echo "::set-output name=default_branch::$(curl -s -H 'Accept: application/vnd.github.v3+json' https://api.github.com/repos/${{ github.repository }}/ | jq -r '.default_branch')"

  phpcs:
    name: PHPCS Check
    runs-on: ubuntu-latest
    needs: get-default-branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      # - name: Check PHPCS issues
      #   run: vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

      - name: Get changed files and lines
        id: changed_files
        run: |
          git diff --name-status origin/${{ needs.get-default-branch.outputs.default_branch }} HEAD | awk '$1 != "D" {print $2}' > changed_files.txt
          cat changed_files.txt | xargs -I % sh -c "git diff -U0 -- % | tail -n +5 | sed '/@@/!d;s/^[^+]/+/;s/^+//;s/[-+].*//' | sort -nu > changed_lines.txt"

      - name: Check PHPCS issues on changed lines
        run: |
          while IFS= read -r file; do
            lines=$(cat changed_lines.txt | grep "$file" | awk '{printf "%s,", $1}' | sed 's/,$//')
            if [ ! -z "$lines" ]; then
              vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- --report=emacs --sniffs=WordPress.Files.FileName,WordPress.Security.EscapeOutput $file --lines="$lines"
            fi
          done < changed_files.txt

  phpcbf:
    name: PHPCBF Fix
    runs-on: ubuntu-latest
    needs: phpcs
    if: ${{ needs.phpcs.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Fix PHPCBF issues
        run: vendor/bin/phpcbf --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

  pre-commit:
    name: Pre-commit hook
    runs-on: ubuntu-latest
    needs: phpcbf

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Check PHPCS issues on changed files
        run: |
          git diff --name-only HEAD^..HEAD | grep '.php$' | xargs -r vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6-
