name: PHP Code Quality

on:
  pull_request:

jobs:
  # phpcbf:
  #   name: PHPCBF Fix
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Composer Update
  #       run: |
  #         composer update

  #     - name: Install PHPCS
  #       run: composer require --dev squizlabs/php_codesniffer

  #     - name: Get modified files and lines
  #       id: changes
  #       uses: tj-actions/changed-files@v42

  #     - name: Fix PHPCBF issues on modified lines
  #       run: |
  #         echo "${{ steps.changes.outputs.modified_files }}" | xargs -I {} sh -c "vendor/bin/phpcbf --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- {}"

  # phpcs:
  #   name: PHPCS Check
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Composer Update
  #       run: |
  #         composer update

  #     - name: Install PHPCS
  #       run: composer require --dev squizlabs/php_codesniffer

  #     - name: Get modified files and lines
  #       id: changed_lines
  #       uses: hestonhoffman/changed-lines@v1

  #     - name: Check PHPCS issues on modified lines
  #       run: |
  #         echo "${{ steps.changed_lines.outputs.changed_lines }}" | jq -r 'to_entries[] | "vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- \(.key) --line-range \(.value | join(","))"'

  phpcs_check:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Get modified files and lines
        id: changes
        uses: hestonhoffman/changed-lines@v1

      - name: Check PHPCS issues on modified lines
        run: |
          modified_files_json="${{ steps.changes.outputs.files }}"
          phpcs_report=""

          for file in $(echo "${modified_files_json}" | jq -r 'keys[]'); do
            lines=$(echo "${modified_files_json}" | jq -r ".${file}[]")
            phpcs_output=$(vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- ${file} | grep -E "^\s*($lines):")
            
            if [ -n "${phpcs_output}" ]; then
              phpcs_report="${phpcs_report}${phpcs_output}\n"
            fi
          done

          if [ -n "${phpcs_report}" ]; then
            echo -e "${phpcs_report}"
            exit 1  # Fail the workflow if there are PHPCS issues
          else
            echo "No PHPCS issues found on modified lines."
          fi
