name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs_check:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Composer Update
        run: |
          composer update

      # - name: Install PHPCS
      #   run: composer require --dev squizlabs/php_codesniffer

      - name: Determine changed files
        id: changed-files
        run: echo "::set-output name=files::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.php$')"

      - name: Run PHPCBF on changed files
        run: |
          echo "${{ steps.changed-files.outputs.files }}" | xargs -n1 vendor/bin/phpcbf
