name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      # - name: Check PHPCS issues
      #   run: vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

      - name: Get list of modified files and lines
        id: modified-files
        run: |
          git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '.php$' > modified_files.txt
          git diff --unified=0 ${{ github.event.before }} ${{ github.sha }} | grep -E '^\+\+\+|^\+\s' | grep -E '^\+\+\+ b/' | sed 's/\+\+\+ b\///' > modified_lines.txt

      - name: Check PHPCS issues on modified lines
        run: |
          while IFS= read -r file; do
            lines=$(grep "$file" modified_lines.txt)
            if [ -n "$lines" ]; then
              vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- "$file" --lines="$lines"
            fi
          done < modified_files.txt

  phpcbf:
    name: PHPCBF Fix
    runs-on: ubuntu-latest
    needs: phpcs
    if: ${{ needs.phpcs.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Fix PHPCBF issues
        run: vendor/bin/phpcbf --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

  pre-commit:
    name: Pre-commit hook
    runs-on: ubuntu-latest
    needs: phpcbf

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Check PHPCS issues on changed files
        run: |
          git diff --name-only HEAD^..HEAD | grep '.php$' | xargs -r vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6-
