name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      # - name: Check PHPCS issues
      #   run: vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

      - name: Check PHPCS issues
        run: |
          git diff --name-only HEAD^..HEAD | grep '.php$' | while read file; do
            git diff HEAD^..HEAD "$file" | grep '^[+-]' | grep -E '^\+[[:space:]]{2,}' | sed 's/^[+]//' > modified_lines.txt
            if [[ -s modified_lines.txt ]]; then
              vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- --report=full --stdin-path="$file" < modified_lines.txt
            fi
          done

  phpcbf:
    name: PHPCBF Fix
    runs-on: ubuntu-latest
    needs: phpcs
    if: ${{ needs.phpcs.result == 'success' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Composer Update
        run: |
          composer update

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Fix PHPCBF issues
        run: vendor/bin/phpcbf --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6- .

  pre-commit:
    name: Pre-commit hook
    runs-on: ubuntu-latest
    needs: phpcbf

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install PHPCS
        run: composer require --dev squizlabs/php_codesniffer

      - name: Check PHPCS issues on changed files
        run: |
          git diff --name-only HEAD^..HEAD | grep '.php$' | xargs -r vendor/bin/phpcs --standard=WordPress --extensions=php --ignore=*/vendor/* --runtime-set testVersion 5.6-
