name: PHP Code Quality

on:
  pull_request:

jobs:
  phpcs_check:
    name: PHPCS Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate diff.txt
        run: git diff --name-only ${{ github.event.before }} ${{ github.sha }} > diff.txt

      - name: Save diff.txt as artifact
        uses: actions/upload-artifact@v2
        with:
          name: diff
          path: diff.txt

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Composer install
        run: |
          composer install

      - name: Install Coverage
        run: composer require --dev exussum12/coverage-checker

      - name: Run PHPCS on changed files
        run: |
          phpcs --standard=psr2 --report=json $(cat diff.txt) > phpcs.json || true
          ./vendor/bin/diffFilter --phpcs diff.txt phpcs.json 100
